{"name": "test_basic_auth[--Not authorized\\n]", "status": "passed", "steps": [{"name": "Initialize URL.", "status": "passed", "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "''"}], "start": 1761485394389, "stop": 1761485394389}, {"name": "Navigating to URL: 'http://the-internet.herokuapp.com/basic_auth'.", "status": "passed", "steps": [{"name": "Navigating to URL: 'http://the-internet.herokuapp.com/basic_auth'.", "status": "passed", "parameters": [{"name": "url", "value": "'http://the-internet.herokuapp.com/basic_auth'"}], "start": 1761485394390, "stop": 1761485394495}], "parameters": [{"name": "url", "value": "'http://the-internet.herokuapp.com/basic_auth'"}], "start": 1761485394389, "stop": 1761485394495}, {"name": "Get authorization message.", "status": "passed", "steps": [{"name": "Get text of element ('css selector', 'div#content p')", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55bdd4a06fea <unknown>\n#1 0x55bdd4484d06 <unknown>\n#2 0x55bdd44d6e6d <unknown>\n#3 0x55bdd44d7101 <unknown>\n#4 0x55bdd45256b4 <unknown>\n#5 0x55bdd44fce3d <unknown>\n#6 0x55bdd4522b3b <unknown>\n#7 0x55bdd44fcbe3 <unknown>\n#8 0x55bdd44c92d2 <unknown>\n#9 0x55bdd44c9f91 <unknown>\n#10 0x55bdd49ca9e8 <unknown>\n#11 0x55bdd49ce84f <unknown>\n#12 0x55bdd49b1ec9 <unknown>\n#13 0x55bdd49cf3f5 <unknown>\n#14 0x55bdd499774f <unknown>\n#15 0x55bdd49f3cc8 <unknown>\n#16 0x55bdd49f3ea3 <unknown>\n#17 0x55bdd4a05f83 <unknown>\n#18 0x7f94a0c9caa4 <unknown>\n#19 0x7f94a0d29c6c <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 113, in get_dynamic_element_text\n    elem = self.wait_for_visibility(locator, timeout)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 70, in wait_for_visibility\n    return self._safe_wait(EC.visibility_of_element_located, locator, timeout)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 28, in _safe_wait\n    return wait.until(ec_method(locator))\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('css selector', 'div#content p')"}, {"name": "timeout", "value": "None"}, {"name": "retry_count", "value": "2"}], "start": 1761485394496, "stop": 1761485404974}], "start": 1761485394496, "stop": 1761485405121}], "attachments": [{"name": "log", "source": "412bc38a-e1a1-48ed-90a3-c07c803a9395-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "192f94ef-4342-4575-a873-8f195702334e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "''"}, {"name": "expected_message", "value": "'Not authorized\n'"}], "start": 1761485394389, "stop": 1761485405121, "uuid": "a2d15da9-8fa0-407c-918f-475c5b74501b", "historyId": "42798e6512954325e5980ba5783125cc", "testCaseId": "1a21bc8c1f3aa66587e32fe54490333a", "fullName": "tests.test_basic_auth_login_scenarios.TestBasicAuth#test_basic_auth", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "Tests Basic Autorization login scenatios"}, {"name": "feature", "value": "Basic Auth"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_basic_auth_login_scenarios"}, {"name": "subSuite", "value": "TestBasicAuth"}, {"name": "host", "value": "runnervmwhb2z"}, {"name": "thread", "value": "5714-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_basic_auth_login_scenarios"}], "titlePath": ["tests", "test_basic_auth_login_scenarios.py", "TestBasicAuth"]}