{"name": "test_basic_auth[wrong-wrong-Not authorized\\n]", "status": "passed", "steps": [{"name": "Initialize URL.", "status": "passed", "parameters": [{"name": "username", "value": "'wrong'"}, {"name": "password", "value": "'wrong'"}], "start": 1761482124903, "stop": 1761482124903}, {"name": "Navigating to URL: 'http://wrong:wrong@the-internet.herokuapp.com/basic_auth'.", "status": "passed", "steps": [{"name": "Navigating to URL: 'http://wrong:wrong@the-internet.herokuapp.com/basic_auth'.", "status": "passed", "parameters": [{"name": "url", "value": "'http://wrong:wrong@the-internet.herokuapp.com/basic_auth'"}], "start": 1761482124903, "stop": 1761482125049}], "parameters": [{"name": "url", "value": "'http://wrong:wrong@the-internet.herokuapp.com/basic_auth'"}], "start": 1761482124903, "stop": 1761482125049}, {"name": "Get authorization message.", "status": "passed", "steps": [{"name": "Get text of element ('css selector', 'div#content p')", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55dee7825fea <unknown>\n#1 0x55dee72a3d06 <unknown>\n#2 0x55dee72f5e6d <unknown>\n#3 0x55dee72f6101 <unknown>\n#4 0x55dee73446b4 <unknown>\n#5 0x55dee731be3d <unknown>\n#6 0x55dee7341b3b <unknown>\n#7 0x55dee731bbe3 <unknown>\n#8 0x55dee72e82d2 <unknown>\n#9 0x55dee72e8f91 <unknown>\n#10 0x55dee77e99e8 <unknown>\n#11 0x55dee77ed84f <unknown>\n#12 0x55dee77d0ec9 <unknown>\n#13 0x55dee77ee3f5 <unknown>\n#14 0x55dee77b674f <unknown>\n#15 0x55dee7812cc8 <unknown>\n#16 0x55dee7812ea3 <unknown>\n#17 0x55dee7824f83 <unknown>\n#18 0x7fa23669caa4 <unknown>\n#19 0x7fa236729c6c <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 113, in get_dynamic_element_text\n    elem = self.wait_for_visibility(locator, timeout)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 70, in wait_for_visibility\n    return self._safe_wait(EC.visibility_of_element_located, locator, timeout)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 28, in _safe_wait\n    return wait.until(ec_method(locator))\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('css selector', 'div#content p')"}, {"name": "timeout", "value": "None"}, {"name": "retry_count", "value": "2"}], "start": 1761482125049, "stop": 1761482135074}], "start": 1761482125049, "stop": 1761482135186}], "attachments": [{"name": "log", "source": "798ed0a1-79d8-46e2-94ca-ede486cdfd7a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "5bf0461f-e626-42a8-9de5-98003962f979-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'wrong'"}, {"name": "password", "value": "'wrong'"}, {"name": "expected_message", "value": "'Not authorized\n'"}], "start": 1761482124903, "stop": 1761482135187, "uuid": "ec5f2ebc-f687-46b3-bbd7-9dd9d5190af8", "historyId": "052b7d57479af7445d0e4cd77a83fa9d", "testCaseId": "1a21bc8c1f3aa66587e32fe54490333a", "fullName": "tests.test_basic_auth_login_scenarios.TestBasicAuth#test_basic_auth", "labels": [{"name": "severity", "value": "normal"}, {"name": "story"}, {"name": "feature", "value": "Basic Auth"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_basic_auth_login_scenarios"}, {"name": "subSuite", "value": "TestBasicAuth"}, {"name": "host", "value": "runnervmwhb2z"}, {"name": "thread", "value": "5668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_basic_auth_login_scenarios"}], "titlePath": ["tests", "test_basic_auth_login_scenarios.py", "TestBasicAuth"]}