{"name": "test_basic_auth[wrong-wrong-Not authorized\\n]", "status": "passed", "description": ".", "steps": [{"name": ".", "status": "passed", "parameters": [{"name": "username", "value": "'wrong'"}, {"name": "password", "value": "'wrong'"}], "start": 1761481229956, "stop": 1761481229956}, {"name": ".", "status": "passed", "steps": [{"name": "Navigating to URL: 'http://wrong:wrong@the-internet.herokuapp.com/basic_auth'.", "status": "passed", "parameters": [{"name": "url", "value": "'http://wrong:wrong@the-internet.herokuapp.com/basic_auth'"}], "start": 1761481229956, "stop": 1761481230027}], "parameters": [{"name": "url", "value": "'http://wrong:wrong@the-internet.herokuapp.com/basic_auth'"}], "start": 1761481229956, "stop": 1761481230027}, {"name": "Get authorization message.", "status": "passed", "steps": [{"name": "Get text of element ('css selector', 'div#content p')", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x556104749fea <unknown>\n#1 0x5561041c7d06 <unknown>\n#2 0x556104219e6d <unknown>\n#3 0x55610421a101 <unknown>\n#4 0x5561042686b4 <unknown>\n#5 0x55610423fe3d <unknown>\n#6 0x556104265b3b <unknown>\n#7 0x55610423fbe3 <unknown>\n#8 0x55610420c2d2 <unknown>\n#9 0x55610420cf91 <unknown>\n#10 0x55610470d9e8 <unknown>\n#11 0x55610471184f <unknown>\n#12 0x5561046f4ec9 <unknown>\n#13 0x5561047123f5 <unknown>\n#14 0x5561046da74f <unknown>\n#15 0x556104736cc8 <unknown>\n#16 0x556104736ea3 <unknown>\n#17 0x556104748f83 <unknown>\n#18 0x7f57cd29caa4 <unknown>\n#19 0x7f57cd329c6c <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 113, in get_dynamic_element_text\n    elem = self.wait_for_visibility(locator, timeout)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 70, in wait_for_visibility\n    return self._safe_wait(EC.visibility_of_element_located, locator, timeout)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 28, in _safe_wait\n    return wait.until(ec_method(locator))\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('css selector', 'div#content p')"}, {"name": "timeout", "value": "None"}, {"name": "retry_count", "value": "2"}], "start": 1761481230027, "stop": 1761481240533}], "start": 1761481230027, "stop": 1761481240560}], "attachments": [{"name": "log", "source": "7c98c52e-c6e1-4df7-accd-d91bbf4a6f0d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9c719d0f-ad7a-4549-8f17-b02c53b34bcc-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'wrong'"}, {"name": "password", "value": "'wrong'"}, {"name": "expected_message", "value": "'Not authorized\n'"}], "start": 1761481229956, "stop": 1761481240560, "uuid": "a79610ac-10f7-47af-9267-efe528c5991c", "historyId": "052b7d57479af7445d0e4cd77a83fa9d", "testCaseId": "1a21bc8c1f3aa66587e32fe54490333a", "fullName": "tests.test_basic_auth_login_scenarios.TestBasicAuth#test_basic_auth", "labels": [{"name": "severity", "value": "normal"}, {"name": "story"}, {"name": "feature"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_basic_auth_login_scenarios"}, {"name": "subSuite", "value": "TestBasicAuth"}, {"name": "host", "value": "runnervmwhb2z"}, {"name": "thread", "value": "5699-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_basic_auth_login_scenarios"}], "titlePath": ["tests", "test_basic_auth_login_scenarios.py", "TestBasicAuth"]}