INFO     root:conftest.py:124 Starting test: test_basic_auth[--Not authorized\n].
INFO     WDM:logger.py:11 xdist worker is: gw1
INFO     WDM:logger.py:11 ====== WebDriver manager ======
INFO     WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
INFO     WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
INFO     WDM:logger.py:11 Driver [/home/runner/.wdm/gw1/drivers/chromedriver/linux64/141.0.7390.122/chromedriver-linux64/chromedriver] found in cache
INFO     root:conftest.py:142 Started recording: tests_recordings/gw1/test_basic_auth[--Not authorized\n]_20251027_135659/test_basic_auth[--Not authorized\n]_20251027_135659.mp4
INFO     root:base_page.py:76 Navigating to URL: https://the-internet.herokuapp.com/.
INFO     root:base_page.py:78 Navigation completed.
INFO     root:base_page.py:57 Waiting for page to load with indicator ('css selector', 'h1.heading') for 10s.
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
INFO     root:base_page.py:62 Page loaded successfully with indicator ('css selector', 'h1.heading').
INFO     root:test_basic_auth_login_scenarios.py:22 Starting Basic Auth test.
INFO     root:basic_auth_page.py:17 .
INFO     root:basic_auth_page.py:25 .
INFO     root:base_page.py:76 Navigating to URL: http://the-internet.herokuapp.com/basic_auth.
INFO     root:base_page.py:78 Navigation completed.
INFO     root:basic_auth_page.py:30 Attempting to get authorization message.
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
ERROR    root:base_page.py:32 Timeout after 10s for locator ('css selector', 'div#content p'): Message: 
Stacktrace:
#0 0x5653f86e0fea <unknown>
#1 0x5653f815ed06 <unknown>
#2 0x5653f81b0e6d <unknown>
#3 0x5653f81b1101 <unknown>
#4 0x5653f81ff6b4 <unknown>
#5 0x5653f81d6e3d <unknown>
#6 0x5653f81fcb3b <unknown>
#7 0x5653f81d6be3 <unknown>
#8 0x5653f81a32d2 <unknown>
#9 0x5653f81a3f91 <unknown>
#10 0x5653f86a49e8 <unknown>
#11 0x5653f86a884f <unknown>
#12 0x5653f868bec9 <unknown>
#13 0x5653f86a93f5 <unknown>
#14 0x5653f867174f <unknown>
#15 0x5653f86cdcc8 <unknown>
#16 0x5653f86cdea3 <unknown>
#17 0x5653f86dff83 <unknown>
#18 0x7f0cae89caa4 <unknown>
#19 0x7f0cae929c6c <unknown>

INFO     root:test_basic_auth_login_scenarios.py:28 Basic Auth test completed successfully.
INFO     root:conftest.py:146 Stopping video recording...
INFO     utils.video_recorder:video_recorder.py:95 Video created: tests_recordings/gw1/test_basic_auth[--Not authorized\n]_20251027_135659/test_basic_auth[--Not authorized\n]_20251027_135659.mp4
INFO     root:conftest.py:102 Quitting driver for browser: chrome.